site_name: DungeonPlanner
site_url: https://h4kor.github.io/dungeon-planner/
site_author: Niko Abeler
site_description: "Dungeon Planning tool for (tabletop) games "
repo_url: "https://github.com/h4kor/dungeon-planner"
edit_uri: "edit/main/docs/"

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide:
    - Installation: user-guide/installation.md
    - First Chamber: user-guide/first_chamber.md
    - Adding Doors: user-guide/add_doors.md
    - Adding Objects: user-guide/add_objects.md

markdown_extensions:
  - attr_list
  - md_in_html
