name: Run Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install GTK
      run: sudo apt-get install -y libgtk-4-dev libadwaita-1-dev build-essential
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
